repo: 'designing-form-errors'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 1
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true

functionality:
  - path: 'index.html'
    noErrors: true
